name: Docker Swarm CI/CD Pipeline

on:
  push:
    branches:
      - main
jobs:
  # -------------------------------------------
  # JOB 1: BUILD & PUSH NESTJS (NODE)
  # -------------------------------------------
  build-nest:
    name: Build & Push NestJS
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and Push Nest Image
        run: |
          # Change this path to wherever your NestJS Dockerfile lives
          cd /home/ubuntu/docker-project-main/nodejs
          docker build -t ${{ secrets.DOCKER_USERNAME }}/nest-backend:${{ github.sha }} .
          docker push ${{ secrets.DOCKER_USERNAME }}/nest-backend:${{ github.sha }}

  # -------------------------------------------
  # JOB 2: BUILD & PUSH FASTAPI (PYTHON)
  # -------------------------------------------
  build-fastapi:
    name: Build & Push FastAPI
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and Push FastAPI Image
        run: |
          # Change this path to wherever your Python Dockerfile lives
          cd /home/ubuntu/docker-project-main/python 
          docker build -t ${{ secrets.DOCKER_USERNAME }}/fastapi-backend:${{ github.sha }} .
          docker push ${{ secrets.DOCKER_USERNAME }}/fastapi-backend:${{ github.sha }}

  # -------------------------------------------
  # JOB 3: DEPLOY BOTH TO SWARM
  # -------------------------------------------
  deploy-to-swarm:
    name: Deploy to Docker Swarm
    # 'needs' ensures this only runs if BOTH builds succeed
    needs: [build-nest, build-fastapi] 
    runs-on: ubuntu-latest
    steps:
      - name: Execute Swarm Deployment on EC2
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ubuntu
          key: ${{ secrets.SERVER_SSH_KEY }}
          script: |
            # Update NestJS Service
            docker service update \
              --image ${{ secrets.DOCKER_USERNAME }}/nest-backend:${{ github.sha }} \
              my_stack_nest_service
            
            # Update FastAPI Service
            docker service update \
              --image ${{ secrets.DOCKER_USERNAME }}/fastapi-backend:${{ github.sha }} \
              my_stack_fastapi_service
